site_name: Demo MkDocs

site_url: https://anngdinh.github.io/demo_mkdocs/
repo_name: 'anngdinh/demo_mkdocs'
repo_url: 'https://github.com/anngdinh/demo_mkdocs'

theme:
  name: material
  logo: images/logo.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
  palette:
    # Palette toggle for light mode
    - scheme: dracula
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - include-markdown
nav:
  - Home: index.md
  - AI:
    - AI Agent: ai/ai-agent.md
  - English:
    - Writing:
        - Task 1: english/writing/task-1.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
